
2020-10-18 18:43:00,242 CRITICAL config_server_log.py Критическая ошибка
2020-10-18 18:43:00,242 ERROR config_server_log.py Ошибка
2020-10-18 18:43:00,242 DEBUG config_server_log.py Отладочная информация
2020-10-18 18:43:00,242 INFO config_server_log.py Информационное сообщение
2020-10-18 19:40:25,459 INFO server.py Запущен сервер, порт для подключений: 8079, адрес с которого принимаются подключения: 192.168.1.51. Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 19:45:44,351 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 19:49:00,992 INFO server.py Установлено соедение с ПК ('127.0.0.1', 49394)
2020-10-18 19:49:00,992 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1603039740.970516, 'user': {'account_name': 'Guest', 'status': 'User is online'}}
2020-10-18 19:49:00,992 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-10-18 19:49:00,993 DEBUG server.py Соединение с клиентом ('127.0.0.1', 49394) закрывается.
2020-10-18 19:55:39,756 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 19:56:07,116 INFO server.py Установлено соедение с ПК ('127.0.0.1', 51612)
2020-10-18 19:56:07,116 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1603040167.116213, 'user': {'account_name': 'Guest', 'status': 'User is online'}}
2020-10-18 19:56:07,116 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-10-18 19:56:07,116 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51612) закрывается.
2020-10-18 20:04:32,180 INFO server.py Установлено соедение с ПК ('127.0.0.1', 54394)
2020-10-18 20:04:32,180 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1603040672.1804938, 'user': {'account_name': 'Guest', 'status': 'User is online'}}
2020-10-18 20:04:32,180 INFO server.py Cформирован ответ клиенту {'response': 200}
2020-10-18 20:04:32,180 DEBUG server.py Соединение с клиентом ('127.0.0.1', 54394) закрывается.
2020-10-18 20:08:11,556 CRITICAL server.py Попытка запуска сервера с указанием неподходящего порта 777777. Допустимы адреса с 1024 до 65535.
2020-10-18 20:10:43,616 INFO server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: 127.0.0.1. Если адрес не указан, принимаются соединения с любых адресов.
